image:
  file: .gitpod.Dockerfile

tasks:
  - name: Web3 Development
    init: |
      npm install
      npx hardhat compile
    command: npm run dev

ports:
  - port: 3000
    onOpen: open-preview
  - port: 8545
    name: Hardhat
    description: Local Blockchain

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-vscode.vscode-typescript-next
    - formulahendry.auto-rename-tag
    - bradlc.vscode-tailwindcss
    - JuanBlanco.solidity
    - tintinweb.solidity-visual-auditor
    - trufflesuite-csi.truffle-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true 